#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-SAX-Base
Version  : 1.08
Release  : 4
URL      : http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-SAX-Base-1.08.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-SAX-Base-1.08.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0
Requires: perl-XML-SAX-Base-doc

%description
XML::SAX::Base is intended for use as a base class for SAX filter modules
and XML parsers generating SAX events.

%package doc
Summary: doc components for the perl-XML-SAX-Base package.
Group: Documentation

%description doc
doc components for the perl-XML-SAX-Base package.


%prep
%setup -q -n XML-SAX-Base-1.08

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/XML/SAX/Base.pm
/usr/lib/perl5/site_perl/5.22.0/XML/SAX/BuildSAXBase.pl
/usr/lib/perl5/site_perl/5.22.0/XML/SAX/Exception.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
